name = "nexusops"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "NEXUS_OPS"
database_name = "nexusops"
database_id = "d7f86c89-708f-4709-99d8-b1f7cec26295"

[vars]
FRONTEND_URL = "https://nexusops.pages.dev"
JWT_ACCESS_EXPIRY = "15m"
JWT_REFRESH_EXPIRY = "7d"
JWT_ACCESS_SECRET = "nexusops-dev-access-secret-min-32-chars-long"
JWT_REFRESH_SECRET = "nexusops-dev-refresh-secret-min-32-chars-long"
